# Generated by Django 6.0.6 on 2026-06-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
